<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/test.proto

namespace Tests\Proto;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFA\x06\x0A\x10proto/test.proto\x12\x04test\"\xBC\x02\x0A\x0EGetTestRequest\x12\x19\x0A\x08str_test\x18\x01 \x01(\x09R\x07strTest\x12\x19\x0A\x08int_test\x18\x02 \x01(\x05R\x07intTest\x12\x1B\x0A\x09bool_test\x18\x03 \x01(\x08R\x08boolTest\x12\x1D\x0A\x0Afloat_test\x18\x04 \x01(\x02R\x09floatTest\x12\x1F\x0A\x0Bdouble_test\x18\x05 \x01(\x01R\x0AdoubleTest\x12\x1D\x0A\x0Abytes_test\x18\x06 \x01(\x0CR\x09bytesTest\x12<\x0A\x08map_test\x18\x07 \x03(\x0B2!.test.GetTestRequest.MapTestEntryR\x07mapTest\x1A:\x0A\x0CMapTestEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0A\x05value\x18\x02 \x01(\x09R\x05value:\x028\x01\"\x07\x0A\x05Empty\"'\x0A\x0BEchoRequest\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message\"(\x0A\x0CEchoResponse\x12\x18\x0A\x07message\x18\x01 \x01(\x09R\x07message2\xF0\x02\x0A\x0BTestService\x125\x0A\x07GetTest\x12\x14.test.GetTestRequest\x1A\x14.test.GetTestRequest\x121\x0A\x08EchoFast\x12\x11.test.EchoRequest\x1A\x12.test.EchoResponse\x121\x0A\x08EchoSlow\x12\x11.test.EchoRequest\x1A\x12.test.EchoResponse\x122\x0A\x16ReturnsInvalidArgument\x12\x0B.test.Empty\x1A\x0B.test.Empty\x12+\x0A\x0FReturnsNotFound\x12\x0B.test.Empty\x1A\x0B.test.Empty\x123\x0A\x17ReturnsPermissionDenied\x12\x0B.test.Empty\x1A\x0B.test.Empty\x12.\x0A\x12ReturnsUnavailable\x12\x0B.test.Empty\x1A\x0B.test.EmptyBJZ,github.com/letamanoir/iris/test-server/proto\xCA\x02\x0BTests\\Proto\xE2\x02\x0BTests\\Protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

